# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.BooleanField(),
        ),
    ]
