# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.BooleanField(default=False),
        ),
    ]
