# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20170525_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='times',
        ),
    ]
