# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_student_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
