# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='date',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
