# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_detail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='end',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
