# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_auto_20170607_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
